# Generated by Django 3.1.3 on 2020-11-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='curForm',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
