# Generated by Django 3.1.3 on 2020-11-17 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20201116_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('played', models.IntegerField()),
                ('won', models.IntegerField()),
                ('drawn', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('gf', models.IntegerField()),
                ('ga', models.IntegerField()),
                ('gd', models.IntegerField()),
                ('points', models.IntegerField()),
                ('curForm', models.CharField(max_length=200, null=True)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='table.team')),
            ],
        ),
    ]
