# Generated by Django 3.1.3 on 2020-11-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_auto_20201117_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='stadium',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
