# Generated by Django 3.1.3 on 2020-11-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_club_stadium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='stadium',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
