# Generated by Django 3.1.3 on 2020-11-17 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0006_auto_20201117_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='table.team'),
        ),
    ]
