# Generated by Django 3.1.3 on 2020-11-18 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0008_club_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=10, null=True)),
                ('teams', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='table.team')),
            ],
        ),
    ]
