# Generated by Django 3.1.3 on 2020-11-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0010_game_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='teams',
        ),
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(null=True, to='table.Team'),
        ),
    ]
