# Generated by Django 3.1.3 on 2020-11-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0011_auto_20201117_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
