# Generated by Django 3.1.3 on 2020-11-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0012_auto_20201117_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='score',
        ),
        migrations.AddField(
            model_name='game',
            name='teamOneGoals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='teamTwoGoals',
            field=models.IntegerField(default=0),
        ),
    ]
