# Generated by Django 3.1.3 on 2020-11-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0013_auto_20201117_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='teamOneGoals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='teamTwoGoals',
            field=models.IntegerField(null=True),
        ),
    ]
