# Generated by Django 3.1.3 on 2020-11-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0014_auto_20201118_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='teamOne',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='teamTwo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
