# Generated by Django 3.1.3 on 2020-11-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0015_auto_20201118_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='teamOne',
            new_name='teamone',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='teamTwo',
            new_name='teamtwo',
        ),
    ]
