# Generated by Django 3.1.3 on 2020-11-18 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0016_auto_20201118_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='date',
            new_name='gameDate',
        ),
    ]
