# Generated by Django 3.1.3 on 2020-11-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0017_auto_20201118_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gameDate',
            new_name='gamedate',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='teamOneGoals',
            new_name='teamonegoals',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='teamTwoGoals',
            new_name='teamtwogoals',
        ),
    ]
