# Generated by Django 3.1.3 on 2020-11-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0018_auto_20201118_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
