# Generated by Django 3.1.3 on 2020-11-19 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0020_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='squad',
            new_name='club',
        ),
    ]
