# Generated by Django 3.1.3 on 2020-11-25 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0023_auto_20201121_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='team',
        ),
        migrations.AddField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='table.club'),
        ),
    ]
