# Generated by Django 3.1.3 on 2020-11-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0024_auto_20201124_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abrev',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
