# Generated by Django 3.1.3 on 2020-12-11 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0026_player_position2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
    ]
